name: CraftWithPy
version: 1.0-SNAPSHOT
api-version: 1.16
main: me.hevelmc.craftwithpy.Main
description: Run Python Code in live on Minecraft
author: Hevel

commands:
  py:
    description: Run the MinecraftWithPython commands